# Generated by Django 5.0.3 on 2024-03-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasKhusus', '0002_alter_nilaisiswa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='NIK Guru')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Guru')),
                ('nomor_induk_guru', models.CharField(max_length=50, verbose_name='Nomor Induk Guru')),
                ('nomor_induk_pegawai', models.CharField(max_length=50, verbose_name='Nomor Induk Pegawai')),
                ('gender', models.BooleanField(default=True, verbose_name='Gender Guru')),
                ('tempat_lahir', models.CharField(max_length=255, verbose_name='Tempat Lahir Guru')),
                ('tanggal_lahir', models.DateTimeField(verbose_name='Tanggal Lahir Guru')),
                ('alamat', models.CharField(max_length=255, verbose_name='Alamat Guru')),
                ('no_telepon', models.CharField(max_length=32, verbose_name='No Telepon Guru')),
                ('agama', models.CharField(max_length=50, verbose_name='Agama Guru')),
                ('tahun_masuk', models.CharField(max_length=4, verbose_name='Tahun Masuk Guru')),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='NIK Karyawan')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Karyawan')),
                ('nomor_induk_pegawai', models.CharField(max_length=50, verbose_name='NIP Karyawan')),
                ('gender', models.BooleanField(default=True, verbose_name='Gender Karyawan')),
                ('tempat_lahir', models.CharField(max_length=255, verbose_name='Tempat Lahir Karyawan')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir Karyawan')),
                ('alamat', models.CharField(max_length=255, verbose_name='Alamat Karyawan')),
                ('no_telepon', models.CharField(max_length=50, verbose_name='No Telepon Karyawan')),
                ('agama', models.CharField(max_length=50, verbose_name='Agama Karyawan')),
                ('tahun_masuk', models.CharField(max_length=4, verbose_name='Tahun Masuk Karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Kurikulum')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Kurikulum')),
                ('tahun_mulai_berlaku', models.CharField(max_length=4, verbose_name='Tahun Kurikulum Mulai Berlaku')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='NIK User')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Kelas')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Kelas')),
                ('tahun', models.CharField(max_length=4, verbose_name='Tahun adanya Kelas')),
                ('ketua_murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.siswa')),
                ('wali_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.guru')),
            ],
        ),
        migrations.CreateModel(
            name='DaftarSiswaKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Daftar Siswa Kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.siswa')),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='KomponenPenilaian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Komponen Penilaian')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Komponen Penilaian')),
                ('bobot', models.IntegerField(verbose_name='Bobot Komponen Penilaian')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.guru')),
            ],
        ),
        migrations.AlterField(
            model_name='nilaisiswa',
            name='komponen_penilaian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.komponenpenilaian'),
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Mata Pelajaran')),
                ('kode', models.CharField(max_length=50, verbose_name='Kode Mata Pelajaran')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Mata Pelajaran')),
                ('tahun_pelaksanaan', models.CharField(max_length=4, verbose_name='Tahun Pelaksanaan Mata Pelajaran')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.kurikulum')),
            ],
        ),
        migrations.AddField(
            model_name='komponenpenilaian',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.matapelajaran'),
        ),
        migrations.CreateModel(
            name='BabPengajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Pengajaran')),
                ('pertemuan_ke', models.IntegerField(verbose_name='Pertemuan Ke-')),
                ('tanggal', models.DateField(verbose_name='Tanggal Bab Pengajaran')),
                ('foto', models.CharField(max_length=50, verbose_name='Foto Pengajaran')),
                ('status', models.IntegerField(verbose_name='Status Pengajaran')),
                ('materi', models.IntegerField(verbose_name='Materi Pengajaran')),
                ('catatan_tambahan', models.CharField(max_length=255, verbose_name='Catatan Tambahan Pengajaran')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Presensi')),
                ('presensi', models.IntegerField(verbose_name='Integer Presensi?')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.matapelajaran')),
                ('pertemuan_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.babpengajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.siswa', to_field='nis')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Feedback')),
                ('feedback', models.CharField(max_length=255, verbose_name='Feedback')),
                ('date', models.DateTimeField(verbose_name='Feedback date')),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.user')),
            ],
        ),
    ]
