# Generated by Django 4.2.11 on 2024-03-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugasKhusus', '0003_guru_karyawan_kurikulum_user_alter_siswa_nis_kelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelasYangDiampuGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID Kelas Yang Diampu')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugasKhusus.kelas')),
            ],
        ),
    ]
