# Generated by Django 4.2.11 on 2024-03-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugasKhusus', '0004_kelasyangdiampuguru'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KelasYangDiampuGuru',
            new_name='MappingGuru',
        ),
    ]
