# Generated by Django 4.2.11 on 2024-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasKhusus', '0006_mappingguru_mata_pelajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babpengajaran',
            name='foto',
            field=models.FileField(upload_to='', verbose_name='Foto Pengajaran'),
        ),
    ]
