# Generated by Django 5.0.3 on 2024-05-06 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugasKhusus', '0008_alter_babpengajaran_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Feedback date'),
        ),
    ]
